---Consultas SQL------

/*a) Empleados en activo que han sido despedidos anteriormente. */
select SSN
from contracts
where end_date>sysdate or end_date is null
INTERSECT
SELECT ssn
FROM CONTRACTS
where ceasing is not null and ceasing not like 'Contract%';




/*b) Proyectos no finalizados cuyo gasto ya se ha excedido de su presupuesto. */

SELECT PROJECTS.IDPROJECT, PROJECTS.BUDGET, SUM(COSTS.SALARY/160) AS BALANCE
FROM REP_LINES 
INNER JOIN PROJECTS
ON REP_LINES.IDPROJECT = PROJECTS.IDPROJECT
INNER JOIN CONTRACTS
ON REP_LINES.SSN = CONTRACTS.SSN
INNER JOIN COSTS
ON CONTRACTS.CAT_NUM = COSTS.CAT_NUM
WHERE PROJECTS.END_DATE>SYSDATE AND CONTRACTS.START_DATE<REP_LINES.REP_DATE AND
(CONTRACTS.END_DATE IS NULL OR CONTRACTS.END_DATE>REP_LINES.REP_DATE) AND
 COSTS.YEAR = TO_NUMBER(TO_CHAR(REP_LINES.REP_DATE, 'YYYY')) 
GROUP BY PROJECTS.IDPROJECT, PROJECTS.BUDGET
HAVING SUM(COSTS.SALARY/160)>BUDGET;




/*c) Empleados activos en el mes de Abril de 2014 que no cogieron vacaciones ese mes*/
SELECT DISTINCT REP_LINES.SSN
FROM REP_LINES
INNER JOIN CONTRACTS
ON REP_LINES.SSN = CONTRACTS.SSN
WHERE CONTRACTS.END_DATE >= TO_DATE('2014_04_01', 'YYYY_MM_DD') AND CONTRACTS.START_DATE <= TO_DATE('2014_04_30', 'YYYY_MM_DD')
minus
SELECT DISTINCT REP_LINES.SSN
FROM REP_LINES
WHERE Task like 'I am on %' and REP_DATE+(DAY-1) >= TO_DATE('2014_04_01', 'YYYY_MM_DD') AND REP_DATE+(DAY-1) <= TO_DATE('2014_04_30', 'YYYY_MM_DD');





/*d) Cuenta total de resultados (balance) por proyecto, ordenada por fecha de finalización*/
SELECT IDPROJECT, END_DATE, TO_CHAR(TOTAL, '9,999,999.99') AS BALANCE
FROM(
WITH SALARIO_EMPLEADO AS(
SELECT REP_LINES.SSN, COSTS.SALARY/160 AS SALARIO, REP_LINES.IDPROJECT, REP_LINES.JOB, REP_LINES.REP_DATE
FROM REP_LINES
INNER JOIN CONTRACTS
ON REP_LINES.SSN = CONTRACTS.SSN
INNER JOIN COSTS
ON COSTS.CAT_NUM = CONTRACTS.CAT_NUM 
WHERE EXTRACT(YEAR FROM REP_LINES.REP_DATE)=COSTS.YEAR AND CONTRACTS.START_DATE<REP_LINES.REP_DATE AND 
(CONTRACTS.END_DATE IS NULL OR CONTRACTS.END_DATE>REP_LINES.REP_DATE)
)
SELECT SALARIO_EMPLEADO.IDPROJECT, PROJECTS.END_DATE, SUM(COSTS.WAGE-SALARIO) AS TOTAL
FROM SALARIO_EMPLEADO
INNER JOIN COSTS
ON SALARIO_EMPLEADO.JOB = COSTS.CAT_NUM
INNER JOIN PROJECTS
ON SALARIO_EMPLEADO.IDPROJECT = PROJECTS.IDPROJECT
WHERE EXTRACT(YEAR FROM SALARIO_EMPLEADO.REP_DATE)=COSTS.YEAR
GROUP BY SALARIO_EMPLEADO.IDPROJECT, PROJECTS.END_DATE
ORDER BY PROJECTS.END_DATE
);


/*e) Empleados con varios periodos de contratación no contiguos*/
select ssn 
from(
select distinct ssn, count(ssn), count(case when ceasing like 'Contract%' then 1 else null end)
from contracts
group by ssn
having count(SSN)>1 and count(case when ceasing like 'Contract%' then 1 else null end)<count(SSN)-1)
INTERSECT
select ssn 
from contracts
where ceasing not like 'Contract%';

