/*DISPARADORES  CATEGORIA A): CATEGORÍA JEFE DE PROYECTO*/

CREATE OR REPLACE TRIGGER T_CATEGORIA_JEFE_PROYECTO
BEFORE 
INSERT OR UPDATE ON PROJECTS
FOR EACH ROW
DECLARE CATEGORIA NUMBER;
BEGIN
     SELECT CAT_NUM INTO CATEGORIA
     FROM CONTRACTS
     WHERE :NEW.MANAGER = CONTRACTS.SSN AND :NEW.END_DATE<=CONTRACTS.END_DATE AND CONTRACTS.START_DATE <= :NEW.START_DATE ;

 if 
     CATEGORIA IN (0,7,8,9)
     THEN RAISE_APPLICATION_ERROR (-20000, 'CATEGORIA JEFE DE PROYECTO INVALIDA');

 END IF;
 exception
 when NO_DATA_FOUND then
 RAISE_APPLICATION_ERROR (-20000, 'CONTRATO INVÁLIDO');


 END;
 
 
 /*DISPARADORES CATEGORIA B): EMPLEADO SOBRECARGADO*/ 
 
CREATE OR REPLACE TRIGGER T_EMPLEADO_SOBRECARGADO
BEFORE
INSERT ON REP_LINES
FOR EACH ROW
DECLARE HORAS_ACTUALES NUMBER DEFAULT 0;
BEGIN 
SELECT COUNT (HOUR) INTO HORAS_ACTUALES
FROM REP_LINES
WHERE SSN =:NEW.SSN AND REP_DATE = :NEW.REP_DATE;

IF (HORAS_ACTUALES)=40
THEN RAISE_APPLICATION_ERROR (-20000, "EMPLEADO SOBRECARGADO");
END IF;
EXCEPTION
WHEN NO_DATA_FOUND THEN
RAISE_APPLICATION_ERROR (-20000, 'DATOS INVÁLIDOS');

END;


/*DISPARADORES CATEGORIA C): FECHAS CONTRATOS*/ 

CREATE OR REPLACE TRIGGER T_FECHAS_CONTRATOS
BEFORE
INSERT ON CONTRACTS
FOR EACH ROW
DECLARE FECHA_FIN DATE DEFAULT TO_DATE('01-01-1900', 'DD-MM-YYYY') ;

BEGIN 
select max(nvl(end_date,to_date('31-12-9999', 'dd-mm-yyyy'))) into fecha_fin
from contracts
WHERE SSN=:NEW.SSN;

IF FECHA_FIN > :NEW.START_DATE
THEN RAISE_APPLICATION_ERROR (-20000, 'FECHA CONTRATO SE SOLAPA');
END IF;
END;

/*DISPARADORES CATEGORIA D): REEMPLAZO JEFE EQUIPO (un jefe equipo solo puede ser reemplazado por un jefe proyecto)*/

CREATE OR REPLACE TRIGGER T_REEMPLAZO_JEFE_EQUIPO
BEFORE
UPDATE OF LEADER ON TEAMS
FOR EACH ROW
DECLARE JEFE_PROYECTO VARCHAR(15);
BEGIN 
SELECT MANAGER INTO JEFE_PROYECTO
FROM PROJECTS
WHERE MANAGER = :NEW.LEADER AND END_DATE>SYSDATE;
EXCEPTION
WHEN NO_DATA_FOUND THEN RAISE_APPLICATION_ERROR (-20000, 'JEFE EQUIPO SOLO PUEDE SER SUSTITUIDO POR UN JEFE PROYECTO');
END;


/*DISPARADOR JEFE DE EQUIPO*/

CREATE OR REPLACE TRIGGER T_CATEGORIA_JEFE_EQUIPO
BEFORE 
INSERT ON TEAMS
FOR EACH ROW
DECLARE CATEGORIA_INVALIDA EXCEPTION;
CATEGORIA NUMBER;
BEGIN
     SELECT CAT_NUM INTO CATEGORIA
     FROM CONTRACTS 
	   WHERE :NEW.LEADER = CONTRACTS.SSN AND CONTRACTS.END_DATE>SYSDATE;

 if 
     CATEGORIA IN (0,1,2,3,4,5)
     then RAISE_APPLICATION_ERROR(-20000, 'CATEGORIA JEFE DE EQUIPO INVALIDA');

 END IF;
 exception
 when NO_DATA_FOUND then
 RAISE_APPLICATION_ERROR (-20000, 'CONTRATO INVÁLIDO');
 END;
 
 /*DISPARADOR JEFE DE EMPLEADO*/
 
 CREATE OR REPLACE TRIGGER T_CATEGORIA_EMPLEADO
BEFORE 
INSERT OR UPDATE OF EMPLOYEE ON MEMBERSHIPS
FOR EACH ROW
DECLARE CATEGORIA NUMBER;
BEGIN

      SELECT CAT_NUM INTO CATEGORIA
      FROM CONTRACTS
      WHERE :NEW.EMPLOYEE = CONTRACTS.SSN;

 if 
     CATEGORIA != :NEW.CAT_PROJECT OR CATEGORIA != :NEW.CAT_PROJECT+1 OR CATEGORIA != :NEW.CAT_PROJECT-1
     then RAISE_APPLICATION_ERROR(-20000, 'CATEGORIA EMPLEADO INVALIDA');

 END IF;
 exception
 when NO_DATA_FOUND then
 RAISE_APPLICATION_ERROR (-20000, 'CONTRATO INVÁLIDO');
 END;
 
 /*DISPARADOR JEFE DE PROYECTO SOBRECARGADO*/
 CREATE OR REPLACE TRIGGER T_JEFE_PROYECTO_SOBRECARGADO
BEFORE
INSERT ON PROJECTS
FOR EACH ROW
DECLARE PROYECTOS_ACTUALES NUMBER;
BEGIN 
SELECT COUNT(IDPROJECT)INTO PROYECTOS_ACTUALES
FROM PROJECTS 
WHERE MANAGER=:NEW.MANAGER AND END_DATE>SYSDATE;


IF (PROYECTOS_ACTUALES)>=3 
THEN RAISE_APPLICATION_ERROR (-20000, 'JEFE DE PROYECTO SOBRECARGADO');
END IF;
END;


--DisparadorFechas contiguas
CREATE OR REPLACE TRIGGER T_FECHAS_CONTRATOS
BEFORE
INSERT ON CONTRACTS
FOR EACH ROW
DECLARE FECHA_FIN DATE DEFAULT TO_DATE('01-01-1900', 'DD-MM-YYYY') ;

BEGIN 
select max(nvl(end_date,'31-12-9999')) into fecha_fin 
from contracts
WHERE SSN=:NEW.SSN;

IF FECHA_FIN >= :NEW.START_DATE 
THEN  DBMS_OUTPUT.PUT_LINE('FECHA CONTRATO SE SOLAPA');
UPDATE CONTRACTS
SET END_DATE = :NEW.START_DATE-1, CEASING = 'Contract termination due to new contract'
WHERE SSN=:NEW.SSN AND FECHA_FIN = nvl(end_date,'31-12-9999')  ;
END IF;
END;
 