/*VISTA NOMINA*/
CREATE OR REPLACE VIEW V_NOMINA(SSN,SALARIO, NUM_TRIENIOS, TOTAL) AS
SELECT CONTRACTS.SSN, COSTS.SALARY, FLOOR(MONTHS_BETWEEN(SYSDATE, CONTRACTS.START_DATE)/36),
       SALARY + FLOOR(MONTHS_BETWEEN(SYSDATE, CONTRACTS.START_DATE)/36)*50
FROM CONTRACTS
INNER JOIN COSTS
ON CONTRACTS.CAT_NUM = COSTS.CAT_NUM
WHERE COSTS.YEAR = EXTRACT (YEAR FROM SYSDATE) AND (CONTRACTS.END_DATE>SYSDATE OR CONTRACTS.END_DATE IS NULL);




/*VISTA PLANTILLA*/
CREATE OR REPLACE VIEW V_PLANTILLA(SSN,BENEFICIO) AS
SELECT SSN, TO_CHAR(TOTAL, '9,999,999.99') 
FROM(
WITH SALARIO_EMPLEADO AS(
SELECT REP_LINES.SSN, REP_LINES.JOB, REP_LINES.REP_DATE AS FECHA, COSTS.SALARY/160 AS SALARIO, REP_LINES.TASK
FROM REP_LINES
INNER JOIN CONTRACTS
ON REP_LINES.SSN = CONTRACTS.SSN
INNER JOIN COSTS
ON CONTRACTS.CAT_NUM = COSTS.CAT_NUM
WHERE EXTRACT (YEAR FROM REP_LINES.REP_DATE)=COSTS.YEAR AND CONTRACTS.START_DATE<REP_LINES.REP_DATE AND 
(CONTRACTS.END_DATE IS NULL OR CONTRACTS.END_DATE>REP_LINES.REP_DATE) )

SELECT SALARIO_EMPLEADO.SSN, SUM(CASE WHEN TASK LIKE 'I am on%' then (-SALARIO) ELSE(COSTS.WAGE-SALARIO) END) AS TOTAL                  
FROM SALARIO_EMPLEADO
INNER JOIN COSTS
ON SALARIO_EMPLEADO.JOB = COSTS.CAT_NUM
WHERE EXTRACT (YEAR FROM SALARIO_EMPLEADO.FECHA)=COSTS.YEAR
GROUP BY SALARIO_EMPLEADO.SSN);


/*VISTA LEADERS TOP 5*/
CREATE OR REPLACE VIEW V_LEADERS_TOP5(MANAGER,BENEFICIO) AS

SELECT MANAGER, TO_CHAR(TOTAL, '9,999,999.99')
FROM(
WITH SALARY_EMPLOYEE AS(
SELECT REP_LINES.SSN, COSTS.SALARY, REP_LINES.IDPROJECT, REP_LINES.JOB, EXTRACT (YEAR FROM REP_LINES.REP_DATE) AS YEAR, REP_LINES.TASK
FROM REP_LINES
INNER JOIN CONTRACTS
ON REP_LINES.SSN = CONTRACTS.SSN
INNER JOIN COSTS 
ON CONTRACTS.CAT_NUM = COSTS.CAT_NUM
WHERE EXTRACT (YEAR FROM REP_LINES.REP_DATE)=COSTS.YEAR AND CONTRACTS.START_DATE<REP_LINES.REP_DATE AND 
(CONTRACTS.END_DATE IS NULL OR CONTRACTS.END_DATE>REP_LINES.REP_DATE)
)

SELECT PROJECTS.IDPROJECT, SUM(CASE WHEN TASK LIKE 'I am on%' then (-SALARY_EMPLOYEE.SALARY/160) ELSE(COSTS.WAGE-SALARY_EMPLOYEE.SALARY/160) END) AS TOTAL,
                           MAX(PROJECTS.MANAGER) AS MANAGER
FROM SALARY_EMPLOYEE
INNER JOIN COSTS
ON SALARY_EMPLOYEE.JOB = COSTS.CAT_NUM
INNER JOIN PROJECTS
ON SALARY_EMPLOYEE.IDPROJECT = PROJECTS.IDPROJECT
WHERE COSTS.YEAR = SALARY_EMPLOYEE.YEAR
GROUP BY PROJECTS.IDPROJECT
ORDER BY SUM(COSTS.WAGE - SALARY_EMPLOYEE.SALARY/160) DESC )
WHERE ROWNUM<=5;



/*VISTA EMPLOYEE OF THE MONTH*/

CREATE OR REPLACE VIEW V_EMPLOYEE_OF_THE_MONTH(EMPLOYEE, MONTH, YEAR, BALANCE) AS

WITH SALARY_EMPLOYEE AS(
SELECT REP_LINES.SSN, REP_LINES.REP_DATE, COSTS.SALARY/160 AS SALARY, REP_LINES.JOB
FROM REP_LINES 
INNER JOIN CONTRACTS
ON REP_LINES.SSN = CONTRACTS.SSN
INNER JOIN COSTS 
ON CONTRACTS.CAT_NUM = COSTS.CAT_NUM
WHERE EXTRACT (YEAR FROM REP_LINES.REP_DATE)=COSTS.YEAR AND 
       CONTRACTS.START_DATE<=REP_LINES.REP_DATE AND (CONTRACTS.END_DATE IS NULL OR CONTRACTS.END_DATE>=REP_LINES.REP_DATE) AND TASK NOT LIKE ('I am on%')
      
),

SSN_EMPLOYEE AS(
SELECT SALARY_EMPLOYEE.SSN, EXTRACT (MONTH FROM SALARY_EMPLOYEE.REP_DATE) AS MONTH,EXTRACT (YEAR FROM SALARY_EMPLOYEE.REP_DATE) AS YEAR, 
       SUM(COSTS.WAGE-SALARY_EMPLOYEE.SALARY) AS TOTAL
FROM SALARY_EMPLOYEE
INNER JOIN COSTS
ON SALARY_EMPLOYEE.JOB = COSTS.CAT_NUM
WHERE EXTRACT(YEAR FROM SALARY_EMPLOYEE.REP_DATE)=COSTS.YEAR
GROUP BY SALARY_EMPLOYEE.SSN, EXTRACT (MONTH FROM SALARY_EMPLOYEE.REP_DATE), EXTRACT (YEAR FROM SALARY_EMPLOYEE.REP_DATE)
),
BALANCE AS(
SELECT MONTH, YEAR, MAX(TOTAL) AS TOTAL
FROM SSN_EMPLOYEE
GROUP BY MONTH, YEAR
)
SELECT DISTINCT SSN_EMPLOYEE.SSN, BALANCE.MONTH, BALANCE.YEAR, TO_CHAR(BALANCE.TOTAL, '9,999,999.99')
FROM BALANCE
INNER JOIN SSN_EMPLOYEE
ON BALANCE.TOTAL = SSN_EMPLOYEE.TOTAL
WHERE BALANCE.MONTH = SSN_EMPLOYEE.MONTH AND BALANCE.YEAR = SSN_EMPLOYEE.YEAR
ORDER BY YEAR, MONTH;


/*VISTA EDAD EMPLEADOS*/

CREATE OR REPLACE VIEW V_EDAD_EMPLEADOS (SSN, EDAD) AS
SELECT SSN, FLOOR(TRUNC(MONTHS_BETWEEN(SYSDATE, BIRTHDATE))/12) AS EDAD
FROM PROFILES;